version: "3.3"
services:
  doali-web:
    image: doali/web:0.2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
    links:
      - db: db 

  db:
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=mysql
